micronaut:
  application:
    name: micronaut-basic
  server:
    port: ${PORT:8080}
    cors:
      enabled: true
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths: "file:styles/${game.style:monochrome},classpath:styles/${game.style:monochrome},classpath:blockrain"

actuators:
  health:
    state: healthy
  ready:
    state: ready
