apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-service
  labels:
    app.kubernetes.io/component: tetris
    app.kubernetes.io/instance: tetris-service-1
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: tetris-service
    app.kubernetes.io/part-of: kubernetes-workshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetris-service-1
      app.kubernetes.io/name: tetris-service
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tetris
        app.kubernetes.io/instance: tetris-service-1
        app.kubernetes.io/managed-by: manual
        app.kubernetes.io/name: tetris-service
        app.kubernetes.io/part-of: kubernetes-workshop

    spec:
      containers:
        - name: tetris
          image: tetris:latest
          imagePullPolicy: Never
          ??? environment
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-service-v2
  labels:
    app.kubernetes.io/component: tetris
    app.kubernetes.io/instance: tetris-service-2
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: tetris-service
    app.kubernetes.io/part-of: kubernetes-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetris-service-2
      app.kubernetes.io/name: tetris-service
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tetris
        app.kubernetes.io/instance: tetris-service-2
        app.kubernetes.io/managed-by: manual
        app.kubernetes.io/name: tetris-service
        app.kubernetes.io/part-of: kubernetes-workshop

    spec:
      containers:
        - name: tetris
          image: tetris:latest
          imagePullPolicy: Never
          ??? environment
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    ???
  name: tetris-service
spec:
  selector:
    ???
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
