apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-service
  labels:
    app.kubernetes.io/component: tetris
    app.kubernetes.io/instance: tetris-service-2
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: tetris-service
    app.kubernetes.io/part-of: kubernetes-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetris-service-2
      app.kubernetes.io/name: tetris-service
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tetris
        app.kubernetes.io/instance: tetris-service-2
        app.kubernetes.io/managed-by: manual
        app.kubernetes.io/name: tetris-service
        app.kubernetes.io/part-of: kubernetes-workshop

    spec:
      containers:
        - name: tetris
          image: tetris:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris-service-v2
  labels:
    app.kubernetes.io/component: tetris
    app.kubernetes.io/instance: tetris-service-1
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: tetris-service
    app.kubernetes.io/part-of: kubernetes-workshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: tetris-service-1
      app.kubernetes.io/name: tetris-service
  template:
    metadata:
      labels:
        app.kubernetes.io/component: tetris
        app.kubernetes.io/instance: tetris-service-1
        app.kubernetes.io/managed-by: manual
        app.kubernetes.io/name: tetris-service
        app.kubernetes.io/part-of: kubernetes-workshop

    spec:
      containers:
        - name: tetris
          image: tetris:latest
          imagePullPolicy: Never
          env:
            - name: style
              value: retro
            - name: actuators_ready_state
              value: ready
            - name: actuators_healty_state
              value: healthy
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 1
            periodSeconds: 1
            successThreshold: 1
            httpGet:
              path: /actuator/ready
              port: http
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: tetris
    app.kubernetes.io/instance: tetris-service-1
    app.kubernetes.io/managed-by: manual
    app.kubernetes.io/name: tetris-service
    app.kubernetes.io/part-of: kubernetes-workshop
  name: tetris-service
spec:
  selector:
    app.kubernetes.io/name: tetris-service
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
