apiVersion: apps/v1
kind: Deployment
metadata:
  name:
spec:
  replicas:
  selector:
    matchLabels:
      app.kubernetes.io/name:
  template:
    metadata:
      labels:
        app.kubernetes.io/name:
    spec:
      containers:
        - name: tetris
          image:
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
